### ISSUE TITLE
snowplow-android-tracker:0.8.0 can not use in google play

### ISSUE THREAD

**Issue by WY1605058341** [xendit/xendit-sdk-android#50]
I am using xendit-sdk-android 2.3.0 version, but after it was released to Google Play.
com.snowplowanalytics:snowplow-android-tracker:0.8.0
Please upgrade to a newer version (1.0.0+). Starting at 00:00 UTC, May 9, 2021, you will not be able to publish new versions of apps that include this SDK version.

**Comment by javiersuweijie** [comment]
@WY1605058341 noted on this. we will be updating a new version in the next few days. 
#51 you can see the PR here
