### ISSUE TITLE
Snowplow shows warning in google play 

### ISSUE THREAD

**Issue by WY1605058341** [xendit/xendit-sdk-android#52]
When I submit an app to Google play for review, a warning is displayed:

“Snowplow Android Tracker”( com.snowplowanalytics The developers of the version 1.4.2 have pointed out that there are serious problems with version 1.4.2. You can consider upgrading before releasing a new version of the app.

The following are the problems pointed out by the SDK developers:
In rare instances, this version can throw a java.util.concurrent.RejectedExecutionException when sending events.

**Comment by javiersuweijie** [comment]
@WY1605058341 thanks for notifying. will update a new version for 2.3.x and 3.0.x in the coming days.
